name: target_classic
environment:
  sdk: '^3.7.0'
dependencies:
  buffer: ^1.2.3
  characters: ^1.4.0
  crypto: ^3.0.6
  dotenv: ^4.2.0
  events_emitter: ^0.6.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
#  dart_lua_ffi: 
#    git:
#      url: https://github.com/Hedwig7s/dart_lua_ffi.git
#      ref: master
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  toml: ^0.16.0
  lints: ^6.0.0
  ffi: ^2.1.4
dev_dependencies:
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5
